### ISSUE TITLE
Nomenclature for labelling echolocation click series (and burst pulses) 

### ISSUE THREAD

**Issue by oliskir** [orcasound/signals-srkw#15]
The latest (Sep 2024) iteration of the HALLO annotation taxonomy, employes the following hierarchical labelling structure for killer whale vocalisations:
```
├── BZ [Buzz]
├── CK [Echolocation click]
├── Rasp [Rasp]
├── SI [Surface Impact]
│   ├── J [Jumping]
│   └── TS [Tail Slap]
└── TC [Tonal Call]
    ├── PC [Pulsed Call]
    │   └── BP [Burst Pulse]
    └── W [Whistle]
```
With additional stereotyped calls (S01, S02, ... etc) nested under PC, but not shown in the diagram. 

What are people's thoughts on this taxonomy and its nested structure, especially in relation to the sound types CK, Rasp, BZ, and BP?

The current "definitions" we have for these four sound types are:

## Rasp
Very fast series of modulated clicks used by the whale to gain higher precision, and it may often be associated with foraging. Used by Bigg's killer whales and possibly also by other ecotypes.  You can still hear/see the individual clicks in a Rasp.

## Buzz
Buzzes are trains of clicks, similar to a Rasp, but so fast that you can't usually distinguish the individual clicks anymore, although this may depend on your spectrogram settings (?). A Buzz occurring after a Rasp or very fast train of echolocation clicks could be an indication of successful foraging. A good rule of thumb is any click train with inter-click-interval (ICI) < 25 ms should be labelled a Buzz.

## Burst Pulse
A burst pulse is when clicks are so close together you cannot distinguish the individual clicks, and it looks tonal.

According to Harald Yurk the sound production mechanism for Burst Pulse is distinct from Rasps and Buzzes, which is why I have nested Burst Pulses under Pulsed Calls (PC) in the diagram above although I'm not sure this is appropriate.

**Comment by oliskir** [comment]
@scottveirs , thanks for suggesting I post this here! What are you thoughts on this?

**Comment by oliskir** [comment]
In Beaked Whales, it appears Rasps are distinguished from Buzzes primarily by their different frequency spectrum:

https://onlinelibrary.wiley.com/doi/10.1111/j.1748-7692.2011.00495.x

Rasps and buzzes are said to have similar click repetition rates (median ICI around 5 ms), but Rasp clicks are frequency modulated (FM) similar to regular echolocation clicks whereas Buzz clicks have little or no frequency modulation.

I wonder if something similar holds true for killer whales?

**Comment by scottveirs** [comment]
Thanks for sharing the evolving and exciting HALLO annotation nomenclature, Oliver @oliskir ! 

First a few thoughts on process and how tools in Github (or otherwise) could facilitate agreements across the US-Canada boundary or various bioacoustic groups (like Orcasound, HALLO, ORCA-SPOT): what if we use Github Discussions for preliminary sharing of ideas, then Issues for changes to the repository itself, i.e `code` or `signal` contributions that move us incrementally towards a new "release" of agreed-upon SRKW signals? Additionally, to get hierarchy and label consistency it may help to go back to the [shared Salish Sea signal dictionary](https://docs.google.com/spreadsheets/d/1pskIEYjIVQH0IPa10UBuAZHKaGsxs02_itSIZ1Z7oAw/edit?gid=0#gid=0) we began building in the first year or so of HALLO-Orcasound collaboration and that I've continued to update (with e.g. proposed Orcasound labels for whistle and clicks/sequences). I've updated the [repo README](https://github.com/orcasound/signals-srkw/blob/main/README.md) to reflect a bit of this proposed process as context and hint at what I see as potential new releases of the repo (e.g. in the next 12 months).

For example, in relation to this issue, you could start with a general Github Discussion topic like "How can HALLO and Orcasound agree upon a nomenclature for broadband impulsive sounds made by SRKWs?" That might allow us to discuss with folks like Harald and Val not only types and sequences of echolocation clicks (individual pulses, slow clicks, fast clicks, buzzes), but also "percussive" sounds (from breaching, tail slaps, pectoral fin slaps) vs cavitation sounds (from rapidly accelerated flukes). 

And then probably it will make sense to initiate sub-discussions regarding potential categories, like "What should we call impulsive sounds that SRKWs generate with their bodies hydro-dynamically?" We in the US lump them all into "percussives" and I don't think many of us know what a breach sounds like vs a tail slap. Your hierarchy uses the term "jump" when we would probably say "breach."

**Comment by scottveirs** [comment]
Second, in terms of immediate first thoughts:

1) RASPS

I'd never heard the term Rasp used for SRKW signals until the most recent HALLO call. Can you all provide an example (recording of one)? If it's only used by Bigg's KWs, then I suppose discussion of that is better placed in a new repository named `signals-biggs` (my preference if it lives in the Orcasound org) or maybe `signals-TKW` if that's consistent with HALLO nomenclature? 

2) BUZZ

I'm leaning towards the idea that an ICI <50ms is a buzz. See this [SRKW ICI Discussion](https://github.com/orcasound/signals-srkw/discussions/14).

3) BURST PULSE

If this sound is different from a `Pulsed Call` (what Orcasound nomenclature simply names a `call`), I'd like to hear a recording. I wonder if it is a redundant term and don't (yet) find it a useful addition to SRKW signal nomenclature.

4) FINALLY

I like your hierarchical presentation and wonder what Orcasound's looks like at the moment. Studying the Google sheet version of a potential shared dictionary, I see something close to this emerging for SRKW signals:

```
signal
|-- call
|     |-- discrete
|     |     |-- S01 (note leading zero!)
|     |     |-- S02...
|     |     |-- S42
|     |-- variable
|     |     |-- S01?
|     |     |-- S02? ...
|     |     |-- S42?
|     |-- aberrant
|-- whistle (maybe there should be discrete/variable/aberrant sub-categories?)
|     |-- SW01
|     |-- ...
|     |-- SW07
|-- click (categories and granularity under discussion!)
|     |-- pulse (a label for an individual echolocation pulse)
|     |-- clicks-slow (a sequence label)
|     |-- clicks-fast (a sequence label)
|     |-- buzz (a sequence label)
|     |-- sweep (a sequence label, primarily for waveform annotation, in which received pulse amplitude rises and then falls)
|-- other
```

**Comment by oliskir** [comment]
I will create a Github Discussion topic to replace this issue. Thanks for the suggestion @scottveirs ! (I wasn't aware of GitHub's discussion page. Looks indeed like a more appropriate place for this type of conversation.)

**Comment by oliskir** [comment]
> Second, in terms of immediate first thoughts:
> 
> 1. RASPS
> 
> I'd never heard the term Rasp used for SRKW signals until the most recent HALLO call. Can you all provide an example (recording of one)? If it's only used by Bigg's KWs, then I suppose discussion of that is better placed in a new repository named `signals-biggs` (my preference if it lives in the Orcasound org) or maybe `signals-TKW` if that's consistent with HALLO nomenclature?
> 
> 2. BUZZ
> 
> I'm leaning towards the idea that an ICI <50ms is a buzz. See this [SRKW ICI Discussion](https://github.com/orcasound/signals-srkw/discussions/14).
> 
> 3. BURST PULSE
> 
> If this sound is different from a `Pulsed Call` (what Orcasound nomenclature simply names a `call`), I'd like to hear a recording. I wonder if it is a redundant term and don't (yet) find it a useful addition to SRKW signal nomenclature.
> 
> 4. FINALLY
> 
> I like your hierarchical presentation and wonder what Orcasound's looks like at the moment. Studying the Google sheet version of a potential shared dictionary, I see something close to this emerging for SRKW signals:
> 
> ```
> signal
> |-- call
> |     |-- discrete
> |     |     |-- S01 (note leading zero!)
> |     |     |-- S02...
> |     |     |-- S42
> |     |-- variable
> |     |     |-- S01?
> |     |     |-- S02? ...
> |     |     |-- S42?
> |     |-- aberrant
> |-- whistle (maybe there should be discrete/variable/aberrant sub-categories?)
> |     |-- SW01
> |     |-- ...
> |     |-- SW07
> |-- click (categories and granularity under discussion!)
> |     |-- pulse (a label for an individual echolocation pulse)
> |     |-- clicks-slow (a sequence label)
> |     |-- clicks-fast (a sequence label)
> |     |-- buzz (a sequence label)
> |     |-- sweep (a sequence label, primarily for waveform annotation, in which received pulse amplitude rises and then falls)
> |-- other
> ```
> 
> I've barely thought about the `other` category (and rarely label any of these sounds), but added to the Gsheet this short list of 6 that might eventually be useful at Orcasound locations (e.g. if we add in-air microphones):
> 
> 1. Percussive
> 2. Cavitation
> 3. Wave
> 4. Blow
> 5. Inhalation
> 6. Rasperry



> Second, in terms of immediate first thoughts:
> 
> 1. RASPS
> 
> I'd never heard the term Rasp used for SRKW signals until the most recent HALLO call. Can you all provide an example (recording of one)? If it's only used by Bigg's KWs, then I suppose discussion of that is better placed in a new repository named `signals-biggs` (my preference if it lives in the Orcasound org) or maybe `signals-TKW` if that's consistent with HALLO nomenclature?
> 
> 2. BUZZ
> 
> I'm leaning towards the idea that an ICI <50ms is a buzz. See this [SRKW ICI Discussion](https://github.com/orcasound/signals-srkw/discussions/14).
> 
> 3. BURST PULSE
> 
> If this sound is different from a `Pulsed Call` (what Orcasound nomenclature simply names a `call`), I'd like to hear a recording. I wonder if it is a redundant term and don't (yet) find it a useful addition to SRKW signal nomenclature.
> 
> 4. FINALLY
> 
> I like your hierarchical presentation and wonder what Orcasound's looks like at the moment. Studying the Google sheet version of a potential shared dictionary, I see something close to this emerging for SRKW signals:
> 
> ```
> signal
> |-- call
> |     |-- discrete
> |     |     |-- S01 (note leading zero!)
> |     |     |-- S02...
> |     |     |-- S42
> |     |-- variable
> |     |     |-- S01?
> |     |     |-- S02? ...
> |     |     |-- S42?
> |     |-- aberrant
> |-- whistle (maybe there should be discrete/variable/aberrant sub-categories?)
> |     |-- SW01
> |     |-- ...
> |     |-- SW07
> |-- click (categories and granularity under discussion!)
> |     |-- pulse (a label for an individual echolocation pulse)
> |     |-- clicks-slow (a sequence label)
> |     |-- clicks-fast (a sequence label)
> |     |-- buzz (a sequence label)
> |     |-- sweep (a sequence label, primarily for waveform annotation, in which received pulse amplitude rises and then falls)
> |-- other
> ```
> 
> I've barely thought about the `other` category (and rarely label any of these sounds), but added to the Gsheet this short list of 6 that might eventually be useful at Orcasound locations (e.g. if we add in-air microphones):
> 
> 1. Percussive
> 2. Cavitation
> 3. Wave
> 4. Blow
> 5. Inhalation
> 6. Rasperry

**Comment by oliskir** [comment]
Moved this issue to the Discussions page:  https://github.com/orcasound/signals-srkw/discussions/16
